version: '3.8'

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        PROJECT_FOLDER_NAME: stridze-tools
      
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_pswd
      - MYSQL_DATABASE=stridze
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=pswd
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: